version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "roadji"
    assignees:
      - "roadji"
    commit-message:
      prefix: "frontend"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Backend dependencies - UPDATED CONFIGURATION
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"  # Changed to Tuesday to spread the load
      time: "09:00"
    open-pull-requests-limit: 15  # Increased limit to handle backlog
    reviewers:
      - "roadji"
    assignees:
      - "roadji"
    commit-message:
      prefix: "backend"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Only ignore truly breaking major updates for core framework packages
      - dependency-name: "flask"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
      # Allow other packages to update more freely, but ignore known problematic ones
      - dependency-name: "celery"
        update-types: ["version-update:semver-major"]  # Celery major updates can be breaking

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "roadji"
    assignees:
      - "roadji"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions" 